#!/usr/bin/awk -f

BEGIN { 
    FS = "," 
    mkheader()
    printf("( ") >"dimensions.tmp"
}

NR != 1 { 
    loc = $1
    piece = $2
    d = $3
    h = $4
    w = $5
    dims = "(" $3 "*" $4 "*" $5 ") + "
    photo = $6
    thumb = "./thumbs/" photo ".jpg"
    jpg   = "./photos/"    photo ".jpg"
    print "    <tr>"
    print "        <td>" loc "</td>"
    print "        <td>" piece "</td>"
    print "        <td>" d  "</td>"
    print "        <td>" h "</td>"
    print "        <td>" w "</td>"
    if (photo == "") { print "        <td>no photo</td>" }
    else { print "        <td><a href=\"" jpg "\"><img src=\"" thumb "\" alt=\"" photo "\"/></a></td>" }
    print "    </tr>"

    if (dims !~ /[?-]/) {
        printf("%s", dims) >"dimensions.tmp"
    }
}

END { 
    print "</table>"
    print "<p>"
    printf("0 ) / 12 / 12 / 12\n") >"dimensions.tmp"
    close("dimensions.tmp")
    "/usr/bin/bc < dimensions.tmp" | getline cf
    print cf " total cubic feet measured"
    system("rm dimensions.tmp")    
}

function mkheader() {
    print "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\""
    print "\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">"
    print "<html>"
    print ""
    print "<head>"
    print "	<title>Ballard Preschool Coop furniture</title>"
    print "    <link rel=\"stylesheet\" type=\"text/css\" href=\"web.css\" />"
    print "</head>"
    print ""
    print "<p>"
    print "csv of this data available <a href=\"./furniture.csv\">here</a>"
    print "</p>"
    print "<p>"
    print "page generated with <a href=\"./csv2htm-tbl\">this</a> script"
    print "</p>"
    print "<p>"
    print "clone this page:"
    print "<code>git clone git://github.com/nbirnel/bpc-furniture.git</code>"
    print "</p>"
    print "<table border=\"1\">"
    print "    <tr>"
    print "        <td>location</td>"
    print "        <td>piece</td>"
    print "        <td>D</td>"
    print "        <td>H</td>"
    print "        <td>W</td>"
    print "        <td>photo</td>"
    print "    </tr>"
}
